kind = "mobile"
previewPath = "/"
title = "AwaazPe"
version = "1.0.0"
id = "artifacts/awaazpe"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
localPort = 23541
name = "expo"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/awaazpe run dev"

[services.env]
PORT = "23541"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/awaazpe", "run", "build"]
run = ["pnpm", "--filter", "@workspace/awaazpe", "run", "serve"]
